name: Format Translations files

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "*/**.json"

env:
  changes: 0

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout the code
        uses: actions/checkout@v3

      # Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      # Verify translation files
      - name: Verify translation files
        run: node ./scripts/verify.js

      # Format translation files
      - name: Verify translation files
        run: node ./scripts/format.js

      # Check for any changes in Dart files
      - name: Check for Dart file changes
        id: git-check
        run: |
          git diff --exit-code -- '*.json' || echo "changes=1" >> $GITHUB_ENV

      # Configure Git
      - name: Configure Git
        if: env.changes == '1'
        run: |
          git config user.name "GitHub Action"
          git config user.email "actions@github.com"

      # Commit changes
      - name: Commit Dart files
        if: env.changes == '1'
        run: |
          git add \*.dart
          git restore .
          git commit -m "chore: format translation files"

      # Rebase before pushing
      - name: Rebase branch
        if: env.changes == '1'
        run: |
          git fetch origin
          git rebase origin/main

      # Push changes
      - name: push Dart files
        if: env.changes == '1'
        run: git push
